StaffManagement.MVC/Models/ApiResponse.cs
namespace StaffManagement.MVC.Models
{
    public class ApiResponse<T>
    {
        public int Code { get; set; }
        public string? Status { get; set; }
        public string? Message { get; set; }
        public int? TotalRecords { get; set; }
        public List<string>? Errors { get; set; }
        public T? Data { get; set; }

        public static ApiResponse<T> Success(T data, string? message = null, int code = 200, int? totalRecords = null)
        {
            return new ApiResponse<T>
            {
                Code = code,
                Status = "success",
                Message = message,
                TotalRecords = totalRecords,
                Data = data
            };
        }

        public static ApiResponse<T> Fail(string message, int code = 400, List<string>? errors = null)
        {
            return new ApiResponse<T>
            {
                Code = code,
                Status = "fail",
                Message = message,
                Errors = errors
            };
        }
    }
}

StaffManagement.MVC/Models/ErrorViewModel.cs
namespace StaffManagement.MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

StaffManagement.MVC/Models/StaffViewModel.cs
namespace StaffManagement.MVC.Models
{
    public class StaffViewModel
    {
        public string StaffId { get; set; }
        public string? FullName { get; set; }
        public DateOnly Birthday { get; set; }
        public int Gender { get; set; }
    }
}

StaffManagement.MVC/Controllers/StaffController.cs
using Microsoft.AspNetCore.Mvc;
using StaffManagement.MVC.DTOs;
using StaffManagement.MVC.Models;
using StaffManagement.MVC.Services;

namespace StaffManagement.MVC.Controllers
{
    public class StaffController : Controller
    {
        private readonly IStaffApiClient _apiClient;
        public StaffController(IStaffApiClient apiClient)
        {
            _apiClient = apiClient;
        }
        [HttpGet]
        public async Task<IActionResult> Index(string? staffId, int? gender, DateOnly? birthdayFrom, DateOnly? birthdayTo)
        {
            IEnumerable<StaffViewModel> staffs;

            if (!string.IsNullOrEmpty(staffId) || gender.HasValue || birthdayFrom.HasValue || birthdayTo.HasValue)
            {
                var searchDto = new StaffSearchDto
                {
                    StaffId = staffId,
                    Gender = gender,
                    birthdayFrom = birthdayFrom?.ToString("yyyy-MM-dd"),
                    birthdayTo = birthdayTo?.ToString("yyyy-MM-dd")
                };

                var responseResults = await _apiClient.SearchAsync(searchDto);
                staffs = responseResults.Data ?? new List<StaffViewModel>();
            }
            else
            {
                var response = await _apiClient.GetAllAsync();
                return View(response.Data ?? new List<StaffViewModel>());
            }
            return View(staffs);
        }

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(StaffViewModel model)
        {
            TempData["Success"] = string.Empty;
            try
            {
                if (!ModelState.IsValid) return View(model);

                var response = await _apiClient.CreateAsync(model);
                if (response.Status != "Success")
                {
                    TempData["ErrorMessage"] = response.Message;
                    return View(model);
                }
                TempData["Success"] = response.Message;
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message.ToString();
                return View(model); 
                
            }

            return RedirectToAction(nameof(Index));

        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            var response = await _apiClient.GetByIdAsync(id);
            if (response.Data == null) return NotFound();
            return View(response.Data);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string id, StaffViewModel model)
        {
            if (!ModelState.IsValid) return View(model);

            var response = await _apiClient.UpdateAsync(id, model);
            if (response.Status == "Success")
                return RedirectToAction(nameof(Index));

            ModelState.AddModelError("", response.Message);
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            var response = await _apiClient.GetByIdAsync(id);
            if (response.Data == null) return NotFound();
            return View(response.Data);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(string staffId)
        {
            var response = await _apiClient.GetByIdAsync(staffId);
            if (response.Data == null) return NotFound();
            var result = _apiClient.DeleteAsync(staffId);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> ExportExcel()
        {
            var fileBytes = await _apiClient.ExportToExcelAsync();
            return File(fileBytes,
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            "StaffList.xlsx");
        }

        [HttpGet]
        public async Task<IActionResult> ExportPdf()
        {
            var fileBytes = await _apiClient.ExportToPdfAsync();
            var fileName = "StaffList.pdf";

            return File(fileBytes, "application/pdf", fileName);
        }
    }
}

StaffManagement.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

StaffManagement.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Staff Management</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/StaffManagement.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Staff Management</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Staff" asp-action="Index">Staff</a>
                        </li>
                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - StaffManagement.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

StaffManagement.MVC/Views/Staff/Create.cshtml
@model StaffManagement.MVC.Models.StaffViewModel
@{
    ViewData["Title"] = "Create";
}

@if (TempData["Success"] != null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        @TempData["Success"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}
@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        @TempData["ErrorMessage"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}
<div class="card shadow-lg border-0 rounded-3" style="width: 700px; margin:auto;">
    
    <div class="card-header bg-primary text-white d-flex justify-content-between align-items-center">
        <h5>Add New Staff</h5>
    </div>
    <div class="card-body">
        <form asp-action="Create" method="post" class="card p-4 shadow-sm">
            <div class="mb-2">
                <label asp-for="StaffId" class="form-label">Staff Id</label>
                <input asp-for="StaffId" class="form-control" maxlength="8" />
                <span asp-validation-for="StaffId" class="text-danger"></span>
            </div>

            <div class="mb-2">
                <label asp-for="FullName" class="form-label">Full Name</label>
                <input asp-for="FullName" class="form-control" maxlength="100" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>

            <div class="mb-2">
                <label asp-for="Birthday" class="form-label"></label>
                <input asp-for="Birthday" class="form-control" type="date" />
                <span asp-validation-for="Birthday" class="text-danger"></span>
            </div>

            <div class="mb-2">
                <label asp-for="Gender" class="form-label"></label>
                <select asp-for="Gender" class="form-select">
                    <option value="1">Male</option>
                    <option value="2">Female</option>
                </select>
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="d-flex justify-content-start gap-2 mt-3">
                <button type="submit" class="btn btn-primary">
                    <i class="fa fa-save"></i> Save
                </button>
                <a asp-action="Index" class="btn btn-secondary">
                    <i class="fa fa-times"></i> Cancel
                </a>
            </div>
        </form>
    </div>
</div>

StaffManagement.MVC/Views/Staff/Delete.cshtml
@model StaffManagement.MVC.Models.StaffViewModel

@{
    ViewData["Title"] = "Delete";
}

<div class="alert alert-danger">
    <p>Are you sure you want to delete this staff?</p>
</div>

<div class="card p-4 shadow-lg">
    
    <dl class="row">
        <dt class="col-sm-3">Staff ID</dt>
        <dd class="col-sm-9">@Model.StaffId</dd>

        <dt class="col-sm-3">Full Name</dt>
        <dd class="col-sm-9">@Model.FullName</dd>

        <dt class="col-sm-3">Birthday</dt>
        <dd class="col-sm-9">@Model.Birthday.ToString("yyyy-MM-dd")</dd>

        <dt class="col-sm-3">Gender</dt>
        <dd class="col-sm-9">@((Model.Gender == 1) ? "Male" : "Female")</dd>
    </dl>
    <hr/>
    <form asp-action="DeleteConfirmed" method="post" class="mt-3">
        <input type="hidden" asp-for="StaffId" />
        <button type="submit" class="btn btn-danger">Delete</button>
        <a asp-action="Index" class="btn btn-secondary">Cancel</a>
    </form>

</div>

StaffManagement.MVC/Views/Staff/Edit.cshtml
@model StaffManagement.MVC.Models.StaffViewModel
@{
    ViewData["Title"] = "Edit";
}

@if (TempData["Success"] != null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        @TempData["Success"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}
@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        @TempData["ErrorMessage"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}
<div class="card shadow-lg border-0 rounded-3" style="width: 700px; margin:auto;">

    <div class="card-header bg-primary text-white d-flex justify-content-between align-items-center">
        <h5>Add New Staff</h5>
    </div>
    <div class="card-body">
        <form asp-action="Edit" method="post" class="card p-4 shadow-sm">
            <div class="mb-2">
                <label asp-for="StaffId" class="form-label">Staff Id</label>
                <input asp-for="StaffId" class="form-control" maxlength="8" />
                <span asp-validation-for="StaffId" class="text-danger"></span>
            </div>

            <div class="mb-2">
                <label asp-for="FullName" class="form-label">Full Name</label>
                <input asp-for="FullName" class="form-control" maxlength="100" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>

            <div class="mb-2">
                <label asp-for="Birthday" class="form-label"></label>
                <input asp-for="Birthday" class="form-control" type="date" />
                <span asp-validation-for="Birthday" class="text-danger"></span>
            </div>

            <div class="mb-2">
                <label asp-for="Gender" class="form-label"></label>
                <select asp-for="Gender" class="form-select">
                    <option value="1">Male</option>
                    <option value="2">Female</option>
                </select>
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="d-flex justify-content-start gap-2 mt-3">
                <button type="submit" class="btn btn-primary">
                    <i class="fa fa-save"></i> Update
                </button>
                <a asp-action="Index" class="btn btn-secondary">
                    <i class="fa fa-times"></i> Cancel
                </a>
            </div>
        </form>
    </div>
</div>

StaffManagement.MVC/Views/Staff/Index.cshtml
@model IEnumerable<StaffManagement.MVC.Models.StaffViewModel>
@{
    ViewData["Title"] = "Index";
}

@if (TempData["Success"] != null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        @TempData["Success"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        @TempData["ErrorMessage"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

<div class="card shadow-lg border-0 rounded-3">
    <div class="card-header bg-primary text-white d-flex justify-content-between align-items-center">
        <h2 class="mb-3" style="margin:auto;">Staff List</h2>
       
    </div>
    <div class="card-body">
        <form asp-action="Index" method="get" class="card p-2 mb-4">
            <div class="row g-3">
                <div class="col-md-3">
                    <label class="form-label">Staff ID</label>
                    <input type="text" name="staffId" class="form-control form-control-sm" placeholder="Enter Staff ID" value="@Context.Request.Query["staffId"]" />
                </div>
                <div class="col-md-3">
                    <label class="form-label">Gender</label>
                        <select name="gender" class="form-select form-select-sm">
                         <option value="">-- All --</option>
                        <option value="1" selected="@(Context.Request.Query["gender"] == "1")">Male</option>
                        <option value="2" selected="@(Context.Request.Query["gender"] == "2")">Female</option>
                    </select>
                </div>
                <div class="col-md-3">
                    <label class="form-label">Birthday From</label>
                    <input type="date" name="birthdayFrom" class="form-control form-control-sm" value="@Context.Request.Query["birthdayFrom"]" placeholder="dd-mm-yyyy" />
                </div>
                <div class="col-md-3">
                    <label class="form-label">Birthday To</label>
                    <input type="date" id="dateto" name="birthdayTo" class="form-control form-control-sm" value="@Context.Request.Query["birthdayTo"]" placeholder="dd-mm-yyyy" />
                </div>
        </div>
        <div class="mt-3">
                <a asp-action="Create" class="btn btn-primary btn-sm">Add Staff</a>
            <button type="submit" class="btn btn-primary btn-sm">Search</button>
            <a asp-action="Index" class="btn btn-secondary btn-sm">Reset</a>
            <a asp-action="ExportExcel" class="btn btn-success btn-sm">Export to Excel</a>
            <a asp-action="ExportPdf" class="btn btn-danger btn-sm">Export to PDF</a>
        </div>
    </form>
        <table class="table table-striped table-bordered table-hover mb-0">
            <thead class="table-primary">
                <tr>
                    <th>Staff ID</th>
                    <th>Full Name</th>
                    <th>Birthday</th>
                    <th>Gender</th>
                    <th style="width: 200px;">Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.StaffId</td>
                        <td>@item.FullName</td>
                        <td>@item.Birthday.ToString("yyyy-MM-dd")</td>
                        <td>@(item.Gender == 1 ? "Male" : "Female")</td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.StaffId" class="btn btn-primary btn-sm">
                                <i class="fa fa-edit"></i> Edit
                            </a>
                            <a asp-action="Delete" asp-route-id="@item.StaffId" class="btn btn-danger btn-sm">
                                <i class="fa fa-trash"></i> Delete
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>